version: '3'

name: davots
services:
    frontend:
        build:
            context: app/
            dockerfile: ./../docker/Dockerfile-frontend
        volumes:
            - ./app/frontend:/app
            - /app/node_modules/
        ports:
            - 3000:3000

    backend:
        build:
            context: app/
            dockerfile: ./../docker/Dockerfile-backend
        volumes:
            - ./app/backend:/app
            - /app/__pycache__/
        ports:
            - 8000:8000
        environment:
            PYTHONUNBUFFERED: 1

